### ISSUE TITLE
transducer memory question?

### ISSUE THREAD

**Issue by xinqipony** [espnet/espnet#1651]
I tried on librispeech with 4 gpu, always CUDA OOM, even if I use a very small model and very small batch.

Is there a recipe I could follow?

thx

**Comment by sw005320** [comment]
How many GPU memory do you have?
Many of our recipes are tuned based on 11GB GPU memory.

**Comment by xinqipony** [comment]
hi,
I use  Tesla P100,  16280MiB , on the same machine, I can train a transformer ASR with espnet, but the transformer transducer always failed as I said

**Comment by sw005320** [comment]
OK. As far as I know, we have not tested transformer transducer with the Librispeech recipe. @b-flo, could you give him some comments.

**Comment by b-flo** [comment]
Hi,

Thanks for your interest! I did try some dataset (voxforge, vivos and ester, a french corpus) but not Librispeech. For all of them I trained with a single 12Gb GPU. I did have a weird memory access issue in one of my runs but it was because of the batch number (I'm trying to pinpoint the problem in warp-transducer).

Some notes though (I'll update if I remember other things):

- More GPUs doesn't mean the memory will be equally divided between GPUs so it won't necessary "fix" your problem.
- Transducer will, because of the joint procedure, easily blow-up memory compared to other models. I don't know the memory requirement given a network config and corpus but if you tried the current (large) config for Transformer with Transformer-Transducer (T-T), I'm not really surprised you met an OOM...
I have a item related to memory reduction in my todo list but it's not a priority. If this is a recurrent problem I'll work on it asap.
- From what I found, T-T behave better with fewer number of layers and units. Did you try to change some parameters?
- VGG2L as bottleneck seems to perform better as bottleneck compared to Conv2D but it requires more memory...
- I did find T-T difficult to tune compared to RNN-T, performance could vary greatly depending on parameters. (Also, @sw005320  I think we really need to extend accuracy to transducer models, notably for T-T)

**Comment by xinqipony** [comment]
@b-flo  this is my config, and I just use linear bottleneck not VGG2L or Conv2D:
adim: 64
aheads: 2
backend: pytorch
batch-bins: 1000
dlayers: 1
dunits: 128
elayers: 2
eunits: 128
joint-dim: 64

**Comment by b-flo** [comment]
Such small model shouldn't failed. Btw, as indicator: I just re-trained vivos with [this config](https://github.com/espnet/espnet/blob/master/egs/vivos/asr1/conf/tuning/transducer/train_transformer_transducer.yaml) and a linear layer instead of vgg2l and end up with max 8Gb used.

Could you share your complete config and log please?

**Comment by sw005320** [comment]
Another possibility is that the input or output length is too long.
We may use BPE to reduce the output length. or prune the long sequences by tuning https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L109-L110, although our transformer and RNN can train the model with these default values.

**Comment by ahmedalbahnasawy** [comment]
I faced the same CUDA OOM using 4 GPU 1080 TI after 2 hours.

**Comment by b-flo** [comment]
Can you share some more details (config, dataset, error, etc) please?
I'm currently doing some experiments in voxforge using a 12Gb TITAN X and didn't meet any OOM with architecture similar to [this one](https://github.com/espnet/espnet/blob/master/egs/voxforge/asr1/conf/tuning/train_pytorch_transformer.yaml) (with batchsize reduced obviously).

Maybe there's a memory leak or a problem somewhere though, I'll investigate when I have time!
@ahmedalbahnasawy @xinqipony could you check you can train [default transducer model(s) in vivos](https://github.com/espnet/espnet/tree/master/egs/vivos/asr1) please (Transformer-Transducer at least in you case)?

**Comment by ahmedalbahnasawy** [comment]
Sorry for the late response 
This is my config file 
dataset==Librispeech
batch-size: 24
maxlen-in: 800
maxlen-out: 150

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
sortagrad: 1
opt: noam
epochs: 30
patience: 0
accum-grad: 4
grad-clip: 5.0

# transformer related
transformer-lr: 10.0
transformer-warmup-steps: 8000
transformer-attn-dropout-rate-encoder: 0.4

# network architecture
## encoder related
etype: transformer
transformer-input-layer: vgg2l
elayers: 6
eunits: 512
dropout-rate: 0.4
## decoder related
dtype: lstm
dlayers: 2
dec-embed-dim: 300
dunits: 512
dropout-rate-decoder: 0.2
dropout-rate-embed-decoder: 0.1
## attention related
adim: 320
aheads: 4
## joint network related
joint-dim: 300

# transducer related
mtlalpha: 1.0 
rnnt-mode: 'rnnt' # switch to 'rnnt-att' to use transducer with attention
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"

**Comment by xinqipony** [comment]
I am using a very big word piece size over 40k, I will try to use a smaller one

**Comment by ahmedalbahnasawy** [comment]
40k for unigram sentiencepeice model its too much try BPE with 32K
but i think the problem is different

**Comment by Gqwert123** [comment]
> I am using a very big word piece size over 40k, I will try to use a smaller one

hi，I had met the same problem. Have you solved this problem ?

**Comment by b-flo** [comment]
Hi,

If you don't specify the network configuration, GPUs (number, vram), dataset used, number of classes, etc, it will be difficult for any of us to guess

**Comment by ahmedalbahnasawy** [comment]
@b-flo is it similar to this issue ? 
https://github.com/espnet/espnet/issues/1860 
you fixed it already by re making transducer.

**Comment by b-flo** [comment]
No, out-of-memory and illegal memory access are different issues. The latter was due to a bug in warp-transducer while the former only indicates a lack of memory.

**Comment by ahmedalbahnasawy** [comment]
illegal memory access it's bug in warp-transducer you are right but when i commented to this issue on march 10 i had this issue: RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /opt/conda/conda- when i was running Transformer transducer.  I might not declare it in a proper way before. Anyway let me retrain T.transducer model on LS and check if it works

**Comment by b-flo** [comment]
If it's an illegal memory you encountered (which is not what @Gqwert123 referred to and I was replying to), you should re-build warp-transducer, yes!

**Comment by Gqwert123** [comment]
> Another possibility is that the input or output length is too long.
> We may use BPE to reduce the output length. or prune the long sequences by tuning https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L109-L110, although our transformer and RNN can train the model with these default values.

Thanks！I have solved my problem by this way.

**Comment by BuaaAlban** [comment]
accum-grad: 4
adim: 64
aheads: 8
backend: pytorch
#batch-bins: 15000000
batch-bins: 100000
dlayers: 2
dropout-rate: 0.1
dunits: 2048
elayers: 8
epochs: 120
eunits: 2048
grad-clip: 5
lsm-weight: 0.1
criterion: loss
mtlalpha: 1.0
model-module: espnet.nets.pytorch_backend.e2e_asr_transducer:E2E
etype: transformer
dtype: transformer
opt: noam
patience: 0
sortagrad: 0
transformer-attn-dropout-rate-encoder: 0.1
transformer-attn-dropout-rate-decoder: 0.1
transformer-init: pytorch
transformer-input-layer: linear
transformer-lr: 10.0
transformer-warmup-steps: 25000


I have also met some OOM problem during training transformer transducer on Librispeech,  I have make batch-bins smaller  to make it run, though it will meet OOM after several steps.
Do you have any suggestions to ease this OOM problem？？？ 
Thanks  a lot.

**Comment by b-flo** [comment]
Hi,

You can reduce a lot of things to reduce memory usage: batch-bins / batch size, number of layers and units in each, adim, aheads, etc. The main limitation in transducer being the joint procedure part. You can also reduce input and output lengths as @sw005320 suggested:

> We may use BPE to reduce the output length. or prune the long sequences by tuning https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L109-L110, although our transformer and RNN can train the model with these default values.

Btw, your config is missing `joint-dim` parameter. You may want to modify it.

**Comment by BuaaAlban** [comment]
> Hi,
> 
> You can reduce a lot of things to reduce memory usage: batch-bins / batch size, number of layers and units in each, adim, aheads, etc. The main limitation in transducer being the joint procedure part. You can also reduce input and output lengths as @sw005320 suggested:
> 
> > We may use BPE to reduce the output length. or prune the long sequences by tuning https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L109-L110, although our transformer and RNN can train the model with these default values.
> 
> Btw, your config is missing `joint-dim` parameter. You may want to modify it.

Thanks for your advice,   I have reduced the number of layers compared to the setting of the original paper.
And the input and output lengths  setting is default '--maxframes 3000 --maxchars 400'.
I have a question about  the joint procedure part , because it is only some FC，why you think it's the limitation?
BTW, I do miss the 'joint-dim' parameter, and do you have some offical documents for batch-bins (It's dynamically changed batch ? how should I change this configure?)
I have reduced the elayer to 6 and dlayer to 1, and it seems okay (safely running 32% of the epoch).

**Comment by b-flo** [comment]
>  have a question about the joint procedure part , because it is only some FC，why you think it's the limitation?

Well the problem is not the FC part, it's the matrices you're manipulating. For example, before applying tanh and last FC the matrix shape is: `(B, max(T), max(U), joint_dim)`. It can easily blow up memory if you have some relatively long input/output lengths

**Comment by BuaaAlban** [comment]
> > have a question about the joint procedure part , because it is only some FC，why you think it's the limitation?
> 
> Well the problem is not the FC part, it's the matrices you're manipulating. For example, before applying tanh and last FC the matrix shape is: `(B, max(T), max(U), joint_dim)`. It can easily blow up memory if you have some relatively long input/output lengths

Thanks a lot, I see. There is an expanding of dimension for the lattice during training. which make it expanded from 3 d tensor to 4 d tensor. And in this process, OOM easily occurred,  do I understand right?

**Comment by b-flo** [comment]
Yes, hidden representation for encoder (`B, max(T), enc_dim`) and decoder (`B, max(U), dec_dim`) are expanded (`B, max(T), 1, enc_dim`, `B, 1, max(U), dec_dim`), linear transformation is applied to both (`enc_dim` -> `joint_dim`, `dec_dim` -> `joint_dim`) and then broadcasting is done. Resulting in the matrix shape I mentioned.

**Comment by BuaaAlban** [comment]
> Yes, hidden representation for encoder (`B, max(T), enc_dim`) and decoder (`B, max(U), dec_dim`) are expanded (`B, max(T), 1, enc_dim`, `B, 1, max(U), dec_dim`), linear transformation is applied to both (`enc_dim` -> `joint_dim`, `dec_dim` -> `joint_dim`) and then broadcasting is done. Resulting in the matrix shape I mentioned.

Thanks a lot, at the same time, it meets OOM again lol, I have change joint-dim from 320 to 240, hope this setting can work.
BTW, transformer transducer seems hard to reproduce due to memory limitaion.( my GPU is 4*16 G, and always meet OOM)

**Comment by b-flo** [comment]
Yeah, most of the papers from the GAFAM using RNN-T or T-T use GPUs/TPUs with a lot of VRAM, some are hard to reproduce. Btw, note that more GPU won't fix the memory problem as batchsize will be multiplied according the number of GPUs before parallelization.

There are several techniques to reduce memory usage in transducer architecture. I already have some work in progress but it's pending until I finish current items (notably beam search and espnet2 port). It may be a bit better in espnet2 though.

**Comment by BuaaAlban** [comment]
> Yeah, most of the papers from the GAFAM and BATX for RNN-T or T-T use GPUs/TPUs with a lot of VRAM, some are hard to reproduce. Btw, note that more GPU won't fix the memory problem as batchsize will be multiplied according the number of GPUs before parallelization.
> 
> There are several techniques to reduce memory usage in transducer architecture. I already have some work in progress but it's pending until I finish current items (notably beam search and espnet2 port). It may be a bit better in espnet2 though.

I still wonder if joint net is the bottleneck of the Memory, why LSTM transducer doesn't have this OOM problem

**Comment by b-flo** [comment]
Obviously the joint procedure is not the only reason you will end up with an OOM, but the procedure is memory-wasteful by "default". Large linear layers, feeding long sequences to RNN (more so bi-RNN), holding temporary large tensors among other things are ones of the most memory consuming things. You also have to take into account batchsize, number of network parameters, etc.

**Comment by b-flo** [comment]
Btw, if you see something done incorrectly or inneficiently feel free to open an issue to point it out! Any help or advice is welcomed :)

**Comment by BuaaAlban** [comment]
> Btw, if you see something done incorrectly or inneficiently feel free to open an issue to point it out! Any help or advice is welcomed :)

Thanks a lot, your work is great, I will point out if I have any suggestion to make it better.

**Comment by kevinghst** [comment]
> Some notes though (I'll update if I remember other things):

> * VGG2L as bottleneck seems to perform better as bottleneck compared to Conv2D but it requires more memory...

Hey there, thanks for the tips!

Quick follow up question regarding bottleneck layer. So I tried both [VGG2L](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/transducer/vgg2l.py) and [Conv2D](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/transformer/subsampling.py#L42) for my conformer transducer, but was not able to observe a significant difference in performance. 

However, I noticed that given the same input and output dimensions (in my case 81 and 512), Conv2D has a lot more parameters:
vgg2l    = 1570240
conv2d = 7346176

Is it possible that I need to increase the size of the VGG2L to that of Conv2D's (such as increasing output channels) in order to observe performance?

Thanks!

**Comment by b-flo** [comment]
Hi,

> Is it possible that I need to increase the size of the VGG2L to that of Conv2D's (such as increasing output channels) in order to observe performance?

Depending on the task, there shouldn't be too much difference using VGG2L or Conv2D bottleneck. I suggest to carefully tune the conformer blocks and training parameters to yield better performance.
Unfortunately I don't have time to compile tips on that subject but stay tuned, we're currently working on SOTA transducer models and it will be easier for users to tune their models :)
