### ISSUE TITLE
Error when run with multi-GPU

### ISSUE THREAD

**Issue by wentaoxandry** [espnet/espnet#1666]
I run code in docker and use multi-GPU (5 gpus), but I always got this error,  I have tried different batch-size, but not working.

File "/espnet/espnet/avpretrain/asr.py", line 218, in update
    self.update_core()
  File "/espnet/espnet/avpretrain/asr.py", line 187, in update_core
    loss = data_parallel(self.model, x, range(self.ngpu)).mean() / self.accum_grad
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 188, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/espnet/espnet/avpretrain/e2e_asr_transformer.py", line 196, in forward
    ahs_pad, ahs_mask = self.aencoder(axs_pad, asrc_mask)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/espnet/espnet/avpretrain/encoder.py", line 113, in forward
    xs, masks = self.embed(xs, masks)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/espnet/espnet/nets/pytorch_backend/transformer/subsampling.py", line 36, in forward
    x = self.conv(x)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM

How can I fix it? Please help me, thank you

**Comment by wentaoxandry** [comment]
Hallo,
I changed some parameters now it works :)

**Comment by sw005320** [comment]
Which parameters did you change?
It might be good information for others.
(I don't have good multiple GPU environments, and cannot test it so much).

**Comment by wentaoxandry** [comment]
I changed the GPUs number to 4 and change batch-size to 20. I have found similar error (#1369 ), so I follow your advice remove the utterances which are too short. I think the too short utterances are the reason for this error.
