### ISSUE TITLE
espnet docker error

### ISSUE THREAD

**Issue by 200987299** [espnet/espnet#2041]
Dear all, 
I was trying to run the run.sh under espnet/docker to install docker image for Espnet. But I got this error:
`Using image espnet/espnet:gpu-cuda10.1-cudnn7-u18.
Executing application in Docker
docker run --gpus '"device=0"' -i --rm --name espnet_gpu0_20200615T1007 -v /home/dee/Documents/espnet/egs:/espnet/egs -v /home/dee/Documents/espnet/espnet:/espnet/espnet -v /home/dee/Documents/espnet/test:/espnet/test -v /home/dee/Documents/espnet/utils:/espnet/utils -v /export/corpora4/CHiME4/CHiME3:/export/corpora4/CHiME4/CHiME3 espnet/espnet:gpu-cuda10.1-cudnn7-u18 /bin/bash -c 'cd /espnet/egs/chime4/asr1; ./run.sh --dlayers 1 --ngpu 1; chmod -R 777 /espnet/egs/chime4/asr1'
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
run.sh done.`

Can someone tells me what is wrong?

Thank you for your help!

**Comment by sw005320** [comment]
@Fhrozen, could you answer it for me?

**Comment by kan-bayashi** [comment]
Maybe this is your docker env issue.
https://github.com/NVIDIA/nvidia-docker/issues/1034#issuecomment-520282450

**Comment by Fhrozen** [comment]
In case that restarting docker service does not work, follow instructions on the comment https://github.com/NVIDIA/nvidia-docker/issues/1034#issuecomment-575882395

Remember to log off and login after re-installing docker.

**Comment by 200987299** [comment]
> @Fhrozen, could you answer it for me?

Thank you for the help!

**Comment by 200987299** [comment]
> Maybe this is your docker env issue.
> [NVIDIA/nvidia-docker#1034 (comment)](https://github.com/NVIDIA/nvidia-docker/issues/1034#issuecomment-520282450)

Thank you for the help! Problem fixed!

**Comment by 200987299** [comment]
> > Maybe this is your docker env issue.
> > [NVIDIA/nvidia-docker#1034 (comment)](https://github.com/NVIDIA/nvidia-docker/issues/1034#issuecomment-520282450)
> 
> Thank you for the help! Problem fixed!

Thank you for the help! Problem fixed!
