### ISSUE TITLE
Ran out of cuda memory when running multi-tts demo. 

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#2575]
I successfully installed ESPNET and the ESPNET notebooks. I also successfully synthesized a single sentence from the multi-speaker model. When I tried to synthesize a second sentence, I ran out of CUDA memory. Do I have to clear out the CUDA memory between sentences, and if so, how do I do that? My cuda device is a GTX-1080 with 12 GB. Here is the error message. 

RuntimeError: CUDA out of memory. Tried to allocate 6.41 GiB (GPU 0; 10.92 GiB total capacity; 7.46 GiB already allocated; 2.83 GiB free; 7.47 GiB reserved in total by PyTorch)

Thanks
Michael Picheny

**Comment by picheny-nyu** [comment]
Found the problem - was using a VERY long wav file as a reference waveform. When I used a shorter file the memory problem went away. In general how long should such file be?

**Comment by sw005320** [comment]
It depends on the model, but we usually assume the training utterance would be less than 20 seconds. So, it would be safe to make the inference condition similar to the training condition.
