### ISSUE TITLE
Conformer-TTS with Model-parallel Training on 24 GB GPUs

### ISSUE THREAD

**Issue by renepeinl** [espnet/espnet#2949]
**Describe the bug**
Hi,
it's more an issue than a bug. We have two machines with 2x Titan RTX 24 GB GPU each. Do you see a way for us to train the Fastspeech2 Conformer model? 
You specified, that you need at least 32 GB of Videoram for the model to train. 
However, the Pytorch documentation sounds as if it wasn't too hard to link two GPUs in order to let larger models fit into the RAM of the GPU. 
https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html

We have a NVLink bridge for both machines
A naive approach would be to simply cut the Conformer model in half and transfer the outputs of the last layer on GPU 1 as input to the first layer on GPU 2. However, it seems the modification to ESPnet ist not trivial to implement something like this.
Any suggestions?
René

**Basic environments:**
 - OS information: Linux 5.8.0-40-generic #45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021 x86_64
- python version: `3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]`
- espnet version: `espnet 0.9.7`
- pytorch version: `pytorch 1.4.0`
- Git hash: `01214cff08cdd737bcab93dd62e127169394d073`
  - Commit date: `Wed Jan 27 05:43:04 2021 +0900`

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 20.04.1 LTS
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
CMake version: version 3.16.3

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 450.102.04
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.4.0
[pip3] torch-complex==0.2.0
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.4.0
[conda] Could not collect

**Task information:**
- Task:TTS
- Recipe: vctk/tts1/conf/tuning/train_xvector_conformer_fastspeech2.yaml
- ESPnet1 or ESPnet2: ESPnet2

**To Reproduce**
1. Train x-vectors according to egs2/TEMPLATE/tts1/README.MD
2. Train tacotron2 model with x-vectors according to egs2/TEMPLATE/tts1/README.MD
3. ./run.sh --stage 7 --use_xvector true --cleaner none --tts_exp exp/tts_train_xvector_tacotron2_raw_char --inference_args "--use_teacher_forcing true" --test_sets "train_nodev train_dev test" ---use_xvector true (according to egs2/TEMPLATE/tts1/README.MD)
4. ./run.sh --stage 5 --train_config conf/tuning/train_xvector_conformer_fastspeech2.yaml --cleaner none --teacher_dumpdir exp/tts_train_xvector_tacotron2_raw_char/inference_use_teacher_forcingtrue_train.loss.ave --tts_stats_dir exp/tts_train_xvector_tacotron2_raw_char/inference_use_teacher_forcingtrue_train.loss.ave/stats --write_collected_feats true --use_xvector true

Error logs (exp/tts_train_xvector_conformer_fastspeech2_raw_char/train.log):
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/projects/espnet/espnet2/tasks/abs_task.py", line 1304, in main_worker
    cls.trainer.run(
  File "/home/user/projects/espnet/espnet2/train/trainer.py", line 208, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/user/projects/espnet/espnet2/train/trainer.py", line 393, in train_one_epoch
    loss, stats, weight = model(**batch)
  File "/home/user/projects/espnet/tools/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/projects/espnet/tools/venv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/user/projects/espnet/tools/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/projects/espnet/espnet2/tts/espnet_model.py", line 104, in forward
    return self.tts(
  File "/home/user/projects/espnet/tools/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/projects/espnet/espnet2/tts/fastspeech2.py", line 408, in forward
    before_outs, after_outs, d_outs, p_outs, e_outs = self._forward(
  File "/home/user/projects/espnet/espnet2/tts/fastspeech2.py", line 521, in _forward
    zs, _ = self.decoder(hs, h_masks)  # (B, Lmax, adim)
  File "/home/user/projects/espnet/tools/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/projects/espnet/espnet/nets/pytorch_backend/conformer/encoder.py", line 223, in forward
    xs, masks = self.encoders(xs, masks)
  File "/home/user/projects/espnet/tools/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/projects/espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/home/user/projects/espnet/tools/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/projects/espnet/espnet/nets/pytorch_backend/conformer/encoder_layer.py", line 119, in forward
    x_att = self.self_attn(x_q, x, x, pos_emb, mask)
  File "/home/user/projects/espnet/tools/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/projects/espnet/espnet/nets/pytorch_backend/transformer/attention.py", line 199, in forward
    matrix_bd = torch.matmul(q_with_bias_v, p.transpose(-2, -1))
RuntimeError: CUDA out of memory. Tried to allocate 502.00 MiB (GPU 0; 23.64 GiB total capacity; 21.13 GiB already allocated; 238.00 MiB free; 22.11 GiB reserved in total by PyTorch)
[workstation4:0/2] 2021-02-08 15:20:11,851 (internal:139) INFO: Internal process exited
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/projects/espnet/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/home/user/projects/espnet/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/home/user/projects/espnet/espnet2/tasks/abs_task.py", line 1049, in main
    while not ProcessContext(processes, error_queues).join():
  File "/home/user/projects/espnet/tools/venv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 110, in join
    raise Exception(
Exception: process 0 terminated with exit code 1
# Accounting: time=30 threads=1
# Ended (code 1) at Mon Feb  8 15:20:12 CET 2021, elapsed time 30 seconds
/usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 11 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d

**Comment by kan-bayashi** [comment]
Reduce `batch_bins` and increase `accume_grad`.
You can refer this config, which requres only 12 GB. 
https://github.com/espnet/espnet/blob/46f1e6b9ea9d2edd002690719e07cc5b97c7e4ac/egs2/jsut/tts1/conf/tuning/train_conformer_fastspeech2.yaml#L91

**Comment by renepeinl** [comment]
Thanks a lot. Your recommendation worked for us. Great tool.
