### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by mikaizhu** [espnet/espnet#3221]
hi ! i'm using espnet2 to run my experiment

recipe: librispeech
GPU:Tesla P40 x1 Total Memory:23G

i'm using command below:
```
cd espnet/egs2/librispeech/asr1
./run.sh --num_splits_lm 20
```

my run.sh config:
```
#!/usr/bin/env bash
# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
set -e
set -u
set -o pipefail

train_set="train_960"
valid_set="dev"
test_sets="test_clean test_other dev_clean dev_other"

asr_config=conf/tuning/train_asr_transformer.yaml
lm_config=conf/tuning/train_lm_transformer2.yaml
inference_config=conf/decode_asr.yaml

./asr.sh \
    --lang en \
    --ngpu 1 \
    --nbpe 5000 \
    --max_wav_duration 30 \
    --speed_perturb_factors "0.9 1.0 1.1" \
    --asr_config "${asr_config}" \
    --lm_config "${lm_config}" \
    --inference_config "${inference_config}" \
    --train_set "${train_set}" \
    --valid_set "${valid_set}" \
    --test_sets "${test_sets}" \
    --lm_train_text "data/${train_set}/text data/local/other_text/text" \
    --bpe_train_text "data/${train_set}/text" "$@"
```

my asr_config, i only changed linear_units to 1:
```
batch_type: numel
batch_bins: 16000000
accum_grad: 4
max_epoch: 200
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: transformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 1
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 1
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
```

my lm_config is below, i only changed layer and unit to 1:

```
# this configuration requires tesla v100-sxm2(32gb) x 16 gpus it takes about 2 days.
use_amp: true
lm: transformer
lm_conf:
    pos_enc: null
    embed_unit: 128
    att_unit: 512
    head: 8
    unit: 1
    layer: 1
    dropout_rate: 0.0

# optimization related
grad_clip: 5.0
batch_type: numel
batch_bins: 500000000
accum_grad: 2
max_epoch: 25

optim: adam
optim_conf:
   lr: 0.005
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 25000

best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10  # 10 is good.
```

bug:
```
2021-05-18 19:18:01,082 (launch:349) INFO: log file: exp/lm_train_lm_transformer2_en_bpe5000/train.log
run.pl: job failed, log is in exp/lm_train_lm_transformer2_en_bpe5000/train.log
Command '['run.pl', '--name', 'exp/lm_train_lm_transformer2_en_bpe5000/train.log', '--gpu', '1', 'exp/lm_train_lm_transformer2_en_bpe5000/train.log', 'python3', '-m', 'espnet2.bin.lm_train', '--ngpu', '1', '--use_preprocessor', 'true', '--bpemodel', 'data/en_token_list/bpe_unigram5000/bpe.model', '--token_type', 'bpe', '--token_list', 'data/en_token_list/bpe_unigram5000/tokens.txt', '--non_linguistic_symbols', 'none', '--cleaner', 'none', '--g2p', 'none', '--valid_data_path_and_name_and_type', 'dump/raw/dev/text,text,text', '--valid_shape_file', 'exp/lm_stats_en_bpe5000/valid/text_shape.bpe', '--fold_length', '150', '--resume', 'true', '--output_dir', 'exp/lm_train_lm_transformer2_en_bpe5000', '--config', 'conf/tuning/train_lm_transformer2.yaml', '--train_data_path_and_name_and_type', 'exp/lm_stats_en_bpe5000/splits20/lm_train.txt,text,text', '--train_shape_file', 'exp/lm_stats_en_bpe5000/splits20/text_shape.bpe', '--multiple_iterator', 'true', '--ngpu', '1', '--multiprocessing_distributed', 'True']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/zwl/miniconda3/envs/asr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zwl/miniconda3/envs/asr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zwl/Desktop/espnet/espnet2/bin/launch.py", line 385, in <module>
    main()
  File "/home/zwl/Desktop/espnet/espnet2/bin/launch.py", line 376, in main
    raise RuntimeError(
RuntimeError: 
################### The last 1000 lines of exp/lm_train_lm_transformer2_en_bpe5000/train.log ###################
# python3 -m espnet2.bin.lm_train --ngpu 1 --use_preprocessor true --bpemodel data/en_token_list/bpe_unigram5000/bpe.model --token_type bpe --token_list data/en_token_list/bpe_unigram5000/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --valid_shape_file exp/lm_stats_en_bpe5000/valid/text_shape.bpe --fold_length 150 --resume true --output_dir exp/lm_train_lm_transformer2_en_bpe5000 --config conf/tuning/train_lm_transformer2.yaml --train_data_path_and_name_and_type exp/lm_stats_en_bpe5000/splits20/lm_train.txt,text,text --train_shape_file exp/lm_stats_en_bpe5000/splits20/text_shape.bpe --multiple_iterator true --ngpu 1 --multiprocessing_distributed True 
# Started at Tue May 18 19:18:01 CST 2021
#
/home/zwl/miniconda3/envs/asr/bin/python3 /home/zwl/Desktop/espnet/espnet2/bin/lm_train.py --ngpu 1 --use_preprocessor true --bpemodel data/en_token_list/bpe_unigram5000/bpe.model --token_type bpe --token_list data/en_token_list/bpe_unigram5000/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --valid_shape_file exp/lm_stats_en_bpe5000/valid/text_shape.bpe --fold_length 150 --resume true --output_dir exp/lm_train_lm_transformer2_en_bpe5000 --config conf/tuning/train_lm_transformer2.yaml --train_data_path_and_name_and_type exp/lm_stats_en_bpe5000/splits20/lm_train.txt,text,text --train_shape_file exp/lm_stats_en_bpe5000/splits20/text_shape.bpe --multiple_iterator true --ngpu 1 --multiprocessing_distributed True
[zwl-desktop] 2021-05-18 19:18:02,957 (lm:198) INFO: Vocabulary size: 5000
[zwl-desktop] 2021-05-18 19:18:02,979 (encoder:163) INFO: encoder self-attention layer type = self-attention
[zwl-desktop] 2021-05-18 19:18:05,275 (abs_task:1114) INFO: pytorch.version=1.8.0, cuda.available=True, cudnn.version=7605, cudnn.benchmark=False, cudnn.deterministic=True
[zwl-desktop] 2021-05-18 19:18:05,276 (abs_task:1115) INFO: Model structure:
ESPnetLanguageModel(
  (lm): TransformerLM(
    (embed): Embedding(5000, 128)
    (encoder): Encoder(
      (embed): Sequential(
        (0): Linear(in_features=128, out_features=512, bias=True)
        (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (2): Dropout(p=0.0, inplace=False)
        (3): ReLU()
        (4): Sequential()
      )
      (encoders): MultiSequential(
        (0): EncoderLayer(
          (self_attn): MultiHeadedAttention(
            (linear_q): Linear(in_features=512, out_features=512, bias=True)
            (linear_k): Linear(in_features=512, out_features=512, bias=True)
            (linear_v): Linear(in_features=512, out_features=512, bias=True)
            (linear_out): Linear(in_features=512, out_features=512, bias=True)
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (feed_forward): PositionwiseFeedForward(
            (w_1): Linear(in_features=512, out_features=1, bias=True)
            (w_2): Linear(in_features=1, out_features=512, bias=True)
            (dropout): Dropout(p=0.0, inplace=False)
            (activation): ReLU()
          )
          (norm1): LayerNorm((512,), eps=1e-12, elementwise_affine=True)
          (norm2): LayerNorm((512,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.0, inplace=False)
        )
      )
      (after_norm): LayerNorm((512,), eps=1e-12, elementwise_affine=True)
    )
    (decoder): Linear(in_features=512, out_features=5000, bias=True)
  )
)

Model summary:
    Class Name: ESPnetLanguageModel
    Total Number of model parameters: 4.33 M
    Number of trainable parameters: 4.33 M (100.0%)
    Size: 17.31 MB
    Type: torch.float32
[zwl-desktop] 2021-05-18 19:18:05,276 (abs_task:1118) INFO: Optimizer:
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    initial_lr: 0.005
    lr: 2e-07
    weight_decay: 0
)
[zwl-desktop] 2021-05-18 19:18:05,276 (abs_task:1119) INFO: Scheduler: WarmupLR(warmup_steps=25000)
[zwl-desktop] 2021-05-18 19:18:05,277 (abs_task:1128) INFO: Saving the configuration in exp/lm_train_lm_transformer2_en_bpe5000/config.yaml
[zwl-desktop] 2021-05-18 19:18:05,668 (abs_task:1466) INFO: [valid] dataset:
ESPnetDataset(
  text: {"path": "dump/raw/dev/text", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f26da5f30d0>)
[zwl-desktop] 2021-05-18 19:18:05,669 (abs_task:1467) INFO: [valid] Batch sampler: NumElementsBatchSampler(N-batch=3, batch_bins=500000000, sort_in_batch=descending, sort_batch=descending)
[zwl-desktop] 2021-05-18 19:18:05,670 (abs_task:1468) INFO: [valid] mini-batch sizes summary: N-batch=3, mean=1850.3, min=172, max=3766
[zwl-desktop] 2021-05-18 19:18:05,784 (abs_task:1466) INFO: [plot_att] dataset:
ESPnetDataset(
  text: {"path": "dump/raw/dev/text", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f26c7bd0040>)
[zwl-desktop] 2021-05-18 19:18:05,784 (abs_task:1467) INFO: [plot_att] Batch sampler: UnsortedBatchSampler(N-batch=5551, batch_size=1, key_file=exp/lm_stats_en_bpe5000/valid/text_shape.bpe, 
[zwl-desktop] 2021-05-18 19:18:05,784 (abs_task:1468) INFO: [plot_att] mini-batch sizes summary: N-batch=3, mean=1.0, min=1, max=1
[zwl-desktop] 2021-05-18 19:18:05,824 (trainer:278) INFO: 1/25epoch started
[zwl-desktop] 2021-05-18 19:18:05,850 (multiple_iter_factory:34) INFO: Building 0th iter-factory...
[zwl-desktop] 2021-05-18 19:18:20,556 (abs_task:1466) INFO: [train] dataset:
ESPnetDataset(
  text: {"path": "exp/lm_stats_en_bpe5000/splits20/lm_train.txt/split.3", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f26c7bd0d90>)
[zwl-desktop] 2021-05-18 19:18:20,557 (abs_task:1467) INFO: [train] Batch sampler: NumElementsBatchSampler(N-batch=513, batch_bins=500000000, sort_in_batch=descending, sort_batch=descending)
[zwl-desktop] 2021-05-18 19:18:20,558 (abs_task:1468) INFO: [train] mini-batch sizes summary: N-batch=513, mean=3966.8, min=64, max=25001
[zwl-desktop] 2021-05-18 19:20:07,227 (trainer:636) INFO: 1epoch:train:1-100batch: iter_time=0.613, forward_time=0.293, loss=4.332, backward_time=0.296, optim_step_time=0.004, optim0_lr0=5.300e-06, train_time=2.427
[zwl-desktop] 2021-05-18 19:21:43,659 (trainer:636) INFO: 1epoch:train:101-200batch: iter_time=0.386, forward_time=0.278, loss=4.206, backward_time=0.292, optim_step_time=0.004, optim0_lr0=1.530e-05, train_time=1.928
[zwl-desktop] 2021-05-18 19:23:25,307 (trainer:636) INFO: 1epoch:train:201-300batch: iter_time=0.422, forward_time=0.288, loss=3.916, backward_time=0.297, optim_step_time=0.005, optim0_lr0=2.530e-05, train_time=2.032
[zwl-desktop] 2021-05-18 19:24:57,573 (trainer:636) INFO: 1epoch:train:301-400batch: iter_time=0.348, forward_time=0.274, loss=3.461, backward_time=0.291, optim_step_time=0.005, optim0_lr0=3.530e-05, train_time=1.845
[zwl-desktop] 2021-05-18 19:26:30,733 (trainer:636) INFO: 1epoch:train:401-500batch: iter_time=0.353, forward_time=0.276, loss=3.247, backward_time=0.292, optim_step_time=0.006, optim0_lr0=4.530e-05, train_time=1.863
[zwl-desktop] 2021-05-18 19:26:42,272 (multiple_iter_factory:34) INFO: Building 1th iter-factory...
[zwl-desktop] 2021-05-18 19:26:56,682 (abs_task:1466) INFO: [train] dataset:
ESPnetDataset(
  text: {"path": "exp/lm_stats_en_bpe5000/splits20/lm_train.txt/split.16", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f266196e070>)
[zwl-desktop] 2021-05-18 19:26:56,682 (abs_task:1467) INFO: [train] Batch sampler: NumElementsBatchSampler(N-batch=514, batch_bins=500000000, sort_in_batch=descending, sort_batch=descending)
[zwl-desktop] 2021-05-18 19:26:56,683 (abs_task:1468) INFO: [train] mini-batch sizes summary: N-batch=514, mean=3959.1, min=41, max=25001
[zwl-desktop] 2021-05-18 19:28:33,249 (trainer:636) INFO: 1epoch:train:501-600batch: iter_time=0.632, forward_time=0.290, loss=3.175, backward_time=0.293, optim_step_time=0.004, optim0_lr0=5.530e-05, train_time=2.450
[zwl-desktop] 2021-05-18 19:30:07,732 (trainer:636) INFO: 1epoch:train:601-700batch: iter_time=0.369, forward_time=0.276, loss=3.131, backward_time=0.291, optim_step_time=0.004, optim0_lr0=6.530e-05, train_time=1.889
[zwl-desktop] 2021-05-18 19:31:50,928 (trainer:636) INFO: 1epoch:train:701-800batch: iter_time=0.446, forward_time=0.285, loss=3.065, backward_time=0.293, optim_step_time=0.004, optim0_lr0=7.530e-05, train_time=2.063
[zwl-desktop] 2021-05-18 19:33:21,914 (trainer:636) INFO: 1epoch:train:801-900batch: iter_time=0.344, forward_time=0.268, loss=3.015, backward_time=0.291, optim_step_time=0.004, optim0_lr0=8.530e-05, train_time=1.819
[zwl-desktop] 2021-05-18 19:34:57,491 (trainer:636) INFO: 1epoch:train:901-1000batch: iter_time=0.376, forward_time=0.278, loss=2.962, backward_time=0.294, optim_step_time=0.004, optim0_lr0=9.530e-05, train_time=1.911
[zwl-desktop] 2021-05-18 19:35:21,315 (multiple_iter_factory:34) INFO: Building 2th iter-factory...
[zwl-desktop] 2021-05-18 19:35:35,704 (abs_task:1466) INFO: [train] dataset:
ESPnetDataset(
  text: {"path": "exp/lm_stats_en_bpe5000/splits20/lm_train.txt/split.6", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f26c7ba0700>)
[zwl-desktop] 2021-05-18 19:35:35,704 (abs_task:1467) INFO: [train] Batch sampler: NumElementsBatchSampler(N-batch=514, batch_bins=500000000, sort_in_batch=descending, sort_batch=descending)
[zwl-desktop] 2021-05-18 19:35:35,705 (abs_task:1468) INFO: [train] mini-batch sizes summary: N-batch=514, mean=3959.1, min=7, max=25001
[zwl-desktop] 2021-05-18 19:36:54,173 (trainer:636) INFO: 1epoch:train:1001-1100batch: iter_time=0.545, forward_time=0.319, loss=2.917, backward_time=0.292, optim_step_time=0.006, optim0_lr0=1.053e-04, train_time=2.333
[zwl-desktop] 2021-05-18 19:38:35,332 (trainer:636) INFO: 1epoch:train:1101-1200batch: iter_time=0.376, forward_time=0.333, loss=2.893, backward_time=0.293, optim_step_time=0.006, optim0_lr0=1.153e-04, train_time=2.023
[zwl-desktop] 2021-05-18 19:40:20,185 (trainer:636) INFO: 1epoch:train:1201-1300batch: iter_time=0.425, forward_time=0.324, loss=2.868, backward_time=0.290, optim_step_time=0.006, optim0_lr0=1.253e-04, train_time=2.097
[zwl-desktop] 2021-05-18 19:41:51,573 (trainer:636) INFO: 1epoch:train:1301-1400batch: iter_time=0.344, forward_time=0.272, loss=2.847, backward_time=0.291, optim_step_time=0.003, optim0_lr0=1.353e-04, train_time=1.827
[zwl-desktop] 2021-05-18 19:43:24,998 (trainer:636) INFO: 1epoch:train:1401-1500batch: iter_time=0.352, forward_time=0.276, loss=2.818, backward_time=0.298, optim_step_time=0.004, optim0_lr0=1.453e-04, train_time=1.868
[zwl-desktop] 2021-05-18 19:44:05,260 (multiple_iter_factory:34) INFO: Building 3th iter-factory...
[zwl-desktop] 2021-05-18 19:44:19,836 (abs_task:1466) INFO: [train] dataset:
ESPnetDataset(
  text: {"path": "exp/lm_stats_en_bpe5000/splits20/lm_train.txt/split.10", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f266196e070>)
[zwl-desktop] 2021-05-18 19:44:19,836 (abs_task:1467) INFO: [train] Batch sampler: NumElementsBatchSampler(N-batch=514, batch_bins=500000000, sort_in_batch=descending, sort_batch=descending)
[zwl-desktop] 2021-05-18 19:44:19,837 (abs_task:1468) INFO: [train] mini-batch sizes summary: N-batch=514, mean=3959.1, min=2, max=25001
[zwl-desktop] 2021-05-18 19:45:21,657 (trainer:636) INFO: 1epoch:train:1501-1600batch: iter_time=0.581, forward_time=0.283, loss=2.789, backward_time=0.293, optim_step_time=0.005, optim0_lr0=1.553e-04, train_time=2.333
[zwl-desktop] 2021-05-18 19:47:03,267 (trainer:636) INFO: 1epoch:train:1601-1700batch: iter_time=0.419, forward_time=0.295, loss=2.778, backward_time=0.293, optim_step_time=0.005, optim0_lr0=1.653e-04, train_time=2.032
[zwl-desktop] 2021-05-18 19:48:45,202 (trainer:636) INFO: 1epoch:train:1701-1800batch: iter_time=0.438, forward_time=0.282, loss=2.765, backward_time=0.291, optim_step_time=0.004, optim0_lr0=1.753e-04, train_time=2.038
[zwl-desktop] 2021-05-18 19:50:24,161 (trainer:636) INFO: 1epoch:train:1801-1900batch: iter_time=0.410, forward_time=0.279, loss=2.741, backward_time=0.292, optim_step_time=0.004, optim0_lr0=1.853e-04, train_time=1.979
[zwl-desktop] 2021-05-18 19:51:54,438 (trainer:636) INFO: 1epoch:train:1901-2000batch: iter_time=0.335, forward_time=0.269, loss=2.722, backward_time=0.292, optim_step_time=0.004, optim0_lr0=1.953e-04, train_time=1.805
Traceback (most recent call last):
  File "/home/zwl/miniconda3/envs/asr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zwl/miniconda3/envs/asr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zwl/Desktop/espnet/espnet2/bin/lm_train.py", line 22, in <module>
    main()
  File "/home/zwl/Desktop/espnet/espnet2/bin/lm_train.py", line 18, in main
    LMTask.main(cmd=cmd)
  File "/home/zwl/Desktop/espnet/espnet2/tasks/abs_task.py", line 976, in main
    cls.main_worker(args)
  File "/home/zwl/Desktop/espnet/espnet2/tasks/abs_task.py", line 1259, in main_worker
    cls.trainer.run(
  File "/home/zwl/Desktop/espnet/espnet2/train/trainer.py", line 284, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/zwl/Desktop/espnet/espnet2/train/trainer.py", line 548, in train_one_epoch
    scaler.scale(loss).backward()
  File "/home/zwl/miniconda3/envs/asr/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/zwl/miniconda3/envs/asr/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(RuntimeError: CUDA out of memory. Tried to allocate 3.86 GiB (GPU 0; 22.38 GiB total capacity; 15.08 GiB already allocated; 1.08 GiB free; 20.60 GiB reserved in total by PyTorch)
# Accounting: time=2046 threads=1
# Ended (code 1) at Tue May 18 19:52:07 CST 2021, elapsed time 2046 seconds
```
when the program runs to stage 7 , it told me OOM.

what should i do to solve this problem, thanks!

**Comment by sw005320** [comment]
This setup is optimized based on Tesla V100-SXM2(32GB) x 16 GPUs according to https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_lm_transformer2.yaml#L1
If you want to run it with your environment, you have to decrease the batchsize (`batch_bins:`) to make it fit your GPU.

**Comment by mikaizhu** [comment]
> This setup is optimized based on Tesla V100-SXM2(32GB) x 16 GPUs according to https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_lm_transformer2.yaml#L1
> If you want to run it with your environment, you have to decrease the batchsize (`batch_bins:`) to make it fit your GPU.

Thanks for replying, I don’t know batch bins is batch size, I just got in touch with asr

**Comment by mikaizhu** [comment]
i just decreasing batch_bins, it works for me
