### ISSUE TITLE
How to change cuda version

### ISSUE THREAD

**Issue by adsf0078** [espnet/espnet#3865]
Dear 

I use two espnets  for different tts developments.
One is the updated version for developing TTS for well-known benhmark dataset and the other one is older version for my customized TTS.

When I installed the updated version in my RTX A5000 GPU-based UBUNTU system, everything  works ok.
But, when I installed the older version in the same system, it has error saying 'no kernel image is avaliable ...'

When I checked the CUDA version in PYTORCH installed by each espnet, 
the former version is 11.3 as

speech/multispk_xvec$ python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.version.cuda
'11.3'

However, the older version is 

Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.version.cuda
'10.2'

In my system, I installed CUDA-11.3 version.
after installing the older version of espnet, the cuda version is changed from 11.3 to 10.2 shown above.
thus, how can I configure to change the pytorch cuda version to 11.3 in the older version of my espnet as the new version.

Your sincerely,

**Comment by kamo-naoyuki** [comment]
Although ESPnet provides own installing system, there are nothing special things. Please follow PyTorch documentation:

https://pytorch.org/get-started/locally/

```
conda install pytorch torchaudio cudatoolkit=11.3 -c pytorch
```

```
pip3 install torch==1.10.0+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

**Comment by adsf0078** [comment]
Hi,

Of course, I followed the routine of installing pytorch at first as

moris@sys11:/data1/moris/espnet_2/tools$conda create -n espnet_2 python=3.7
moris@sys11:/data1/moris/espnet_2/tools$conda activate espnet_2
(espnet_2)moris@sys11:/data1/moris/espnet_2/tools$ conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done
...
...

---> At this time the torch and cuda version are 1.10.1 and 11.3, respectively, as

(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$ python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.10.1'
>>> torch.version.cuda
'11.3'
>>>quit()

---> but after full installation of the espnet as follows

(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$ ./setup_anaconda.sh /data1/moris/anaconda3 espnet_2 3.7
(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$ CONDA_TOOLS_DIR=$(dirname ${CONDA_EXE})/..
(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$ ./setup_anaconda.sh ${CONDA_TOOLS_DIR} espnet_2 3.7
(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$make TH_VERSION=1.10.0 CUDA_VERSION=11.3
...
...
...
Successfully installed chainer-6.0.0 protobuf-3.7.1 typing-3.7.4.3
# chainer=6.0.0 depends on typing<=3.6.6, but this causes the following error when installing some modules. e.g. fairseq
# AttributeError: type object 'Callable' has no attribute '_abc_registry'
# "typing" modules is not required for python>=3.6, so uninstall here
. ./activate_python.sh && python3 -m pip uninstall -y typing
Found existing installation: typing 3.7.4.3
Uninstalling typing-3.7.4.3:
  Successfully uninstalled typing-3.7.4.3
touch chainer.done
. ./activate_python.sh; . ./extra_path.sh; python3 check_install.py
[x] python=3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)  [GCC 9.4.0]

Python modules:
[x] torch=1.7.1
[x] torch cuda=10.2
[x] torch cudnn=7605
[x] torch nccl
[x] chainer=6.0.0
[ ] chainer cuda
[ ] chainer cudnn
[ ] cupy
/data1/moris/anaconda3/envs/espnet_2/lib/python3.7/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
[x] torchaudio=0.7.2
[x] torch_optimizer=0.3.0
[ ] warpctc_pytorch
[ ] warprnnt_pytorch
[ ] chainer_ctc
[ ] pyopenjtalk
[ ] tdmelodic_pyopenjtalk
[ ] kenlm
[ ] mmseg
[x] espnet=0.9.6
[ ] fairseq
[ ] phonemizer
[ ] gtn
[ ] s3prl
[ ] transformers

Executables:
[x] sclite
[x] sph2pipe
[ ] PESQ
[ ] BeamformIt

INFO:
Use 'installers/install_warp-ctc.sh' to install warpctc_pytorch
Use 'installers/install_warp-transducer.sh' to install warprnnt_pytorch
Use 'installers/install_chainer_ctc.sh' to install chainer_ctc
Use 'installers/install_pyopenjtalk.sh' to install pyopenjtalk
Use 'installers/install_tdmelodic_pyopenjtalk.sh' to install tdmelodic_pyopenjtalk
Use 'installers/install_kenlm.sh' to install kenlm
Use 'installers/install_py3mmseg.sh' to install mmseg
Use 'installers/install_fairseq.sh' to install fairseq
Use 'installers/install_phonemizer.sh' to install phonemizer
Use 'installers/install_gtn.sh' to install gtn
Use 'installers/install_s3prl.sh' to install s3prl
Use 'installers/install_transformers.sh' to install transformers
Use 'installers/install_pesq.sh' to install PESQ
Use 'installers/install_beamformit.sh' to install BeamformIt

--> After full installation of the older version of espnet, the versions of torch and cuda are automatically downgraded 1.7.1 and 10.2, respectively, as follows

(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$ python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.7.1'
>>> torch.version.cuda
'10.2'

Unfortunately, my GPU RTX A5000 does not support CUDA-10.2. 
So I have to change this to CUDA-11.3 to run the older espnet version.
I want to know where the downgrade of the cuda version to 10.2 is determined in the installation procedure.
That is, I want to change '[x] torch cuda=10.2' to [x] torch cuda=11.3' in the above installation report.
Please note that I copied the whole ./tools directory of the newer version of espnet (eg, espnet) to the older espnet (espnet_2), but this different installation still occurred.

Your sincerely.

**Comment by kamo-naoyuki** [comment]
After setup is done, please install pytorch.

**Comment by adsf0078** [comment]
Hi,

Thank you for your quick reply.
I followed your recommendation as follows.
Unfortunately, after installing the pytorch, I found a new error at the run phase as shown in below.

(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$conda install pytorch=1.10.0 torchvision torchaudio cudatoolkit=11.3 -c pytorch
...
...

(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$ . ./activate_python.sh; python3 check_install.py
[x] python=3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)  [GCC 9.4.0]

Python modules:
[x] torch=1.10.0
[x] torch cuda=11.3
[x] torch cudnn=8200
[x] torch nccl
[x] chainer=6.0.0
[ ] chainer cuda
[ ] chainer cudnn
[ ] cupy
[x] torchaudio=0.10.0
[x] torch_optimizer=0.3.0
[ ] warpctc_pytorch
[ ] warprnnt_pytorch
[ ] chainer_ctc
[ ] pyopenjtalk
[ ] tdmelodic_pyopenjtalk
[ ] kenlm
[ ] mmseg
[x] espnet=0.9.6
[ ] fairseq
[ ] phonemizer
[ ] gtn
[ ] s3prl
[ ] transformers

Executables:
[ ] sclite
[ ] sph2pipe
[ ] PESQ
[ ] BeamformIt

INFO:
Use 'installers/install_warp-ctc.sh' to install warpctc_pytorch
Use 'installers/install_warp-transducer.sh' to install warprnnt_pytorch
Use 'installers/install_chainer_ctc.sh' to install chainer_ctc
Use 'installers/install_pyopenjtalk.sh' to install pyopenjtalk
Use 'installers/install_tdmelodic_pyopenjtalk.sh' to install tdmelodic_pyopenjtalk
Use 'installers/install_kenlm.sh' to install kenlm
Use 'installers/install_py3mmseg.sh' to install mmseg
Use 'installers/install_fairseq.sh' to install fairseq
Use 'installers/install_phonemizer.sh' to install phonemizer
Use 'installers/install_gtn.sh' to install gtn
Use 'installers/install_s3prl.sh' to install s3prl
Use 'installers/install_transformers.sh' to install transformers
Use 'installers/install_sctk.sh' to install sclite
Use 'installers/install_sph2pipe.sh' to install sph2pipe
Use 'installers/install_pesq.sh' to install PESQ
Use 'installers/install_beamformit.sh' to install BeamformIt
(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$

(espnet_2) moris@sys11:/data1/moris/espnet_2/egs2/singlespeech/conv$ ./run.sh
2021-12-16T13:37:00 (tts.sh:188:main) ./tts.sh --lang en --feats_type raw --fs 22050 --n_fft 1024 --n_shift 256 --token_type phn --cleaner en --g2p g2p_en --train_config conf/train.yaml --inference_config conf/decode.yaml --train_set tr_no_dev --valid_set dev --test_sets eval1 --srctexts data/tr_no_dev/text --audio_format wav
2021-12-16T13:37:01 (tts.sh:425:main) Stage 4: Generate token_list from data/tr_no_dev/text
/data1/moris/anaconda3/envs/espnet_2/bin/python3 /data1/moris/espnet_2/espnet2/bin/tokenize_text.py --token_type phn -f 2- --input dump/raw/srctexts --output data/token_list/phn_en_g2p_en/tokens.txt --non_linguistic_symbols none --cleaner en --g2p g2p_en --write_vocabulary true --add_symbol '<blank>:0' --add_symbol '<unk>:1' --add_symbol '<sos/eos>:-1'
2021-12-16 13:37:01,986 (tokenize_text:170) INFO: OOV rate = 0.0 %
2021-12-16T13:37:02 (tts.sh:454:main) Stage 5: TTS collect stats: train_set=dump/raw/tr_no_dev, valid_set=dump/raw/dev
2021-12-16T13:37:02 (tts.sh:530:main) Generate 'exp/tts_stats_raw_phn_en_g2p_en/run.sh'. You can resume the process from stage 5 using this script
2021-12-16T13:37:02 (tts.sh:534:main) TTS collect_stats started... log: 'exp/tts_stats_raw_phn_en_g2p_en/logdir/stats.*.log'
Traceback (most recent call last):
  File "/data1/moris/anaconda3/envs/espnet_2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data1/moris/anaconda3/envs/espnet_2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/moris/espnet_2/espnet2/bin/tts_train.py", line 2, in <module>
    from espnet2.tasks.tts import TTSTask
  File "/data1/moris/espnet_2/espnet2/tasks/tts.py", line 17, in <module>
    from espnet2.tasks.abs_task import AbsTask
  File "/data1/moris/espnet_2/espnet2/tasks/abs_task.py", line 62, in <module>
    from espnet2.train.iterable_dataset import IterableESPnetDataset
  File "/data1/moris/espnet_2/espnet2/train/iterable_dataset.py", line 67, in <module>
    class IterableESPnetDataset(IterableDataset):
  File "/data1/moris/anaconda3/envs/espnet_2/lib/python3.7/site-packages/torch/utils/data/_typing.py", line 273, in __new__
    return super().__new__(cls, name, bases, namespace, **kwargs)  # type: ignore[call-overload]
  File "/data1/moris/anaconda3/envs/espnet_2/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/data1/moris/anaconda3/envs/espnet_2/lib/python3.7/site-packages/torch/utils/data/_typing.py", line 374, in _dp_init_subclass
    ", but found {}".format(sub_cls.__name__, _type_repr(hints['return'])))
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of IterableESPnetDataset, but found typing.Iterable[typing.Tuple[typing.Union[str, int], typing.Dict[str, numpy.ndarray]]]

**Comment by adsf0078** [comment]
> After setup is done, please install pytorch.

Hi,

Thank you for your quick reply.
I followed your recommendation as follows.
Unfortunately, after installing the pytorch, I found a new error at the run phase as shown in below.

(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$conda install pytorch=1.10.0 torchvision torchaudio cudatoolkit=11.3 -c pytorch
...
...

(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$ . ./activate_python.sh; python3 check_install.py
[x] python=3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)  [GCC 9.4.0]

Python modules:
[x] torch=1.10.0
[x] torch cuda=11.3
[x] torch cudnn=8200
[x] torch nccl
[x] chainer=6.0.0
[ ] chainer cuda
[ ] chainer cudnn
[ ] cupy
[x] torchaudio=0.10.0
[x] torch_optimizer=0.3.0
[ ] warpctc_pytorch
[ ] warprnnt_pytorch
[ ] chainer_ctc
[ ] pyopenjtalk
[ ] tdmelodic_pyopenjtalk
[ ] kenlm
[ ] mmseg
[x] espnet=0.9.6
[ ] fairseq
[ ] phonemizer
[ ] gtn
[ ] s3prl
[ ] transformers

Executables:
[ ] sclite
[ ] sph2pipe
[ ] PESQ
[ ] BeamformIt

INFO:
Use 'installers/install_warp-ctc.sh' to install warpctc_pytorch
Use 'installers/install_warp-transducer.sh' to install warprnnt_pytorch
Use 'installers/install_chainer_ctc.sh' to install chainer_ctc
Use 'installers/install_pyopenjtalk.sh' to install pyopenjtalk
Use 'installers/install_tdmelodic_pyopenjtalk.sh' to install tdmelodic_pyopenjtalk
Use 'installers/install_kenlm.sh' to install kenlm
Use 'installers/install_py3mmseg.sh' to install mmseg
Use 'installers/install_fairseq.sh' to install fairseq
Use 'installers/install_phonemizer.sh' to install phonemizer
Use 'installers/install_gtn.sh' to install gtn
Use 'installers/install_s3prl.sh' to install s3prl
Use 'installers/install_transformers.sh' to install transformers
Use 'installers/install_sctk.sh' to install sclite
Use 'installers/install_sph2pipe.sh' to install sph2pipe
Use 'installers/install_pesq.sh' to install PESQ
Use 'installers/install_beamformit.sh' to install BeamformIt
(espnet_2) moris@sys11:/data1/moris/espnet_2/tools$

(espnet_2) moris@sys11:/data1/moris/espnet_2/egs2/singlespeech/conv$ ./run.sh
2021-12-16T13:37:00 (tts.sh:188:main) ./tts.sh --lang en --feats_type raw --fs 22050 --n_fft 1024 --n_shift 256 --token_type phn --cleaner en --g2p g2p_en --train_config conf/train.yaml --inference_config conf/decode.yaml --train_set tr_no_dev --valid_set dev --test_sets eval1 --srctexts data/tr_no_dev/text --audio_format wav
2021-12-16T13:37:01 (tts.sh:425:main) Stage 4: Generate token_list from data/tr_no_dev/text
/data1/moris/anaconda3/envs/espnet_2/bin/python3 /data1/moris/espnet_2/espnet2/bin/tokenize_text.py --token_type phn -f 2- --input dump/raw/srctexts --output data/token_list/phn_en_g2p_en/tokens.txt --non_linguistic_symbols none --cleaner en --g2p g2p_en --write_vocabulary true --add_symbol '<blank>:0' --add_symbol '<unk>:1' --add_symbol '<sos/eos>:-1'
2021-12-16 13:37:01,986 (tokenize_text:170) INFO: OOV rate = 0.0 %
2021-12-16T13:37:02 (tts.sh:454:main) Stage 5: TTS collect stats: train_set=dump/raw/tr_no_dev, valid_set=dump/raw/dev
2021-12-16T13:37:02 (tts.sh:530:main) Generate 'exp/tts_stats_raw_phn_en_g2p_en/run.sh'. You can resume the process from stage 5 using this script
2021-12-16T13:37:02 (tts.sh:534:main) TTS collect_stats started... log: 'exp/tts_stats_raw_phn_en_g2p_en/logdir/stats.*.log'
Traceback (most recent call last):
  File "/data1/moris/anaconda3/envs/espnet_2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data1/moris/anaconda3/envs/espnet_2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/moris/espnet_2/espnet2/bin/tts_train.py", line 2, in <module>
    from espnet2.tasks.tts import TTSTask
  File "/data1/moris/espnet_2/espnet2/tasks/tts.py", line 17, in <module>
    from espnet2.tasks.abs_task import AbsTask
  File "/data1/moris/espnet_2/espnet2/tasks/abs_task.py", line 62, in <module>
    from espnet2.train.iterable_dataset import IterableESPnetDataset
  File "/data1/moris/espnet_2/espnet2/train/iterable_dataset.py", line 67, in <module>
    class IterableESPnetDataset(IterableDataset):
  File "/data1/moris/anaconda3/envs/espnet_2/lib/python3.7/site-packages/torch/utils/data/_typing.py", line 273, in __new__
    return super().__new__(cls, name, bases, namespace, **kwargs)  # type: ignore[call-overload]
  File "/data1/moris/anaconda3/envs/espnet_2/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/data1/moris/anaconda3/envs/espnet_2/lib/python3.7/site-packages/torch/utils/data/_typing.py", line 374, in _dp_init_subclass
    ", but found {}".format(sub_cls.__name__, _type_repr(hints['return'])))
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of IterableESPnetDataset, but found typing.Iterable[typing.Tuple[typing.Union[str, int], typing.Dict[str, numpy.ndarray]]]

**Comment by kamo-naoyuki** [comment]
I see. The bug is fixed in the current version.

To use old espnet, you need to fix it by yourself. Please change `Iterable ` to `Iterator `.

**Comment by adsf0078** [comment]
> I see. The bug is fixed in the current version.
> 
> To use old espnet, you need to fix it by yourself. Please change `Iterable ` to `Iterator ` in `espnet2/train/iterable_dataset.py` .

I solved this problem.
Thanks to your reply.
