### ISSUE TITLE
Cannot find CUDA after installation under CUDA 11.2

### ISSUE THREAD

**Issue by underdogliu** [espnet/espnet#5629]
**Describe the issue**
Following an earlier issue about python version. This time I stick with Python 3.8.
I found that after installing the espnet following the instruction given, I cannot use cuda on my node in the computing cluster, like shown below:
```
$ python
Python 3.8.18 (default, Sep 11 2023, 13:40:15)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
/home/smg/xuecliu/envs/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /opt/conda/conda-bld/pytorch_1695392036766/work/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
False
>>>
```

I also found cuda is not installed
**Show the `check_install.py` status by using the following command**
```
(espnet) xuecliu@gpuhost13:~/espnet/tools$ python3 check_install.py
[x] python=3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0]

Python modules:
[x] torch=2.1.0
/home/smg/xuecliu/envs/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/cuda/__init__.p
y:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found ver
sion 11020). Please update your GPU driver by downloading and installing a new version from the
 URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to in
stall a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered
 internally at /opt/conda/conda-bld/pytorch_1695392036766/work/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[ ] torch cuda
[x] torch cudnn=8902
[x] torch nccl
[x] chainer=6.0.0
[ ] chainer cuda
[ ] chainer cudnn
[ ] cupy
[x] torchaudio=2.1.0
[x] torch_optimizer=0.3.0
[ ] warprnnt_pytorch
[ ] chainer_ctc
[ ] pyopenjtalk
[ ] tdmelodic_pyopenjtalk
[ ] kenlm
[ ] mmseg
[x] espnet=202310
[x] numpy=1.23.5
[ ] fairseq
[ ] phonemizer
[ ] gtn
[ ] s3prl
[ ] transformers
[ ] speechbrain
[ ] k2
[ ] longformer
[ ] nlg-eval
[ ] datasets
[ ] pykeops
[ ] whisper
[ ] RawNet3
[ ] reazonspeech
[ ] muskits
```

Below is my `nvidia-smi`:
```

```Mon Jan 22 15:45:44 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-PCIE-40GB      On   | 00000000:61:00.0 Off |                    0 |
| N/A   32C    P0    33W / 250W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Basic environments:**
 - OS information: Linux
 - python version: 3.8.18
 - espnet version: 202310
 - Git hash: `40b3deecd1aa8eaa1702e4a6f4c86bf2ac250de6`
  - Commit date: `Mon Jan 22 14:19:41 2024 +0900`
 - pytorch version: 2.1.0
You can obtain them by the following command
```

**Environments from `torch.utils.collect_env`:**
```
PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.2 LTS (x86_64)
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.27

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-18-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: A100-PCIE-40GB
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           2
NUMA node(s):        2
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               49
Model name:          AMD EPYC 7302 16-Core Processor
Stepping:            0
CPU MHz:             1466.539
CPU max MHz:         3000.0000
CPU min MHz:         1500.0000
BogoMIPS:            6000.23
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            16384K
NUMA node0 CPU(s):   0-15,32-47
NUMA node1 CPU(s):   16-31,48-63
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.1.0
[pip3] torch-complex==0.4.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==2.1.0
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-service               2.4.0            py38h5eee18b_1
[conda] mkl_fft                   1.3.8            py38h5eee18b_0
[conda] mkl_random                1.2.4            py38hdb19cb5_0
[conda] numpy                     1.23.5           py38hf6e8229_1
[conda] numpy-base                1.23.5           py38h060ed82_1
[conda] pytorch                   2.1.0           py3.8_cuda12.1_cudnn8.9.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                2.1.0                py38_cu121    pytorch
[conda] torchtriton               2.1.0                      py38    pytorch
```

**To Reproduce**
Simply install espnet following instructions and run python.

**Comment by sw005320** [comment]
```
/home/smg/xuecliu/envs/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/cuda/__init__.p
y:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found ver
sion 11020). Please update your GPU driver by downloading and installing a new version from the
 URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to in
stall a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered
 internally at /opt/conda/conda-bld/pytorch_1695392036766/work/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
```
This might be a reason.
Can you test it with the older PyTorch version or update your GPU driver?

**Comment by underdogliu** [comment]
@sw005320  Yes I have wiped out the past environment, tested pytorch 1.12.1 with CUDA 11.2 and it works.

I think this is related to my CUDA driver being too old.

Only if necessary, here is the environment that works for CUDA 11.2 and driver 460.32.03:
```
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.2 LTS (x86_64)
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.27

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-18-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.12.1
[pip3] torch-complex==0.4.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.12.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.6.2              hfc3e2af_12    conda-forge
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-service               2.4.0            py38h5eee18b_1
[conda] mkl_fft                   1.3.8            py38h5eee18b_0
[conda] mkl_random                1.2.4            py38hdb19cb5_0
[conda] numpy                     1.23.5           py38hf6e8229_1
[conda] numpy-base                1.23.5           py38h060ed82_1
[conda] pytorch                   1.12.1          py3.8_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.12.1               py38_cu116    pytorch
[conda] torchtriton               2.1.0                      py38    pytorch
```

**Comment by sw005320** [comment]
Sounds good.
I close this issue then.
