### ISSUE TITLE
CUDA out of memory appears when fine-tuning wav2vec2-base model

### ISSUE THREAD

**Issue by WZLHQ** [espnet/espnet#5652]
Hi
When fine-tuning the wav2vec2-base model, CUDA out of memory error appears as follows:
*  File "/home/espnet/tools/miniconda/envs/espnet-1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/espnet/espnet2/asr/espnet_model.py", line 260, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/espnet/espnet2/asr/espnet_model.py", line 431, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(speech, speech_lengths) # modified code
  File "/home/espnet/tools/miniconda/envs/espnet-1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/espnet/espnet2/asr/encoder/wav2vec2_encoder.py", line 116, in forward
    masks = make_pad_mask(ilens).to(xs_pad.device)
  File "/home/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 168, in make_pad_mask
    return _make_pad_mask_traceable(lengths, xs, length_dim, maxlen)
  File "/home/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 249, in _make_pad_mask_traceable
    mask = triu_onnx(mask)[1:, :-1]  # onnx cannot handle diagonal argument.
  File "/home/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 261, in triu_onnx
    return x * mask
RuntimeError: CUDA out of memory. Tried to allocate 7.11 GiB (GPU 0; 23.69 GiB total capacity; 15.69 GiB already allocated; 2.67 GiB free; 19.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I tried many solutions:
* set a smaller batch size, NOT work;
* set max_split_size_mb to be 64, 128, NOT work;

I have spent nearly three days to figure out this error. I am really confused why this error appears. please help me!

I install fairseq using following code:
* cd <main root of espent>/tools
* . ./activate_python.sh && ./installers/install_fairseq.sh

I install espnet following https://espnet.github.io/espnet/installation.html

Task: ASR;
Recipe: I instantiate a recipe for my private dataset;

base enviroment:
* torch: 1.11.0+cu113
* ubuntu 22.04   i7 6800k   3090GPU
* latest fairseq and espnet

my asr config yaml ile is as follows:
encoder: wav2vec2
encoder_conf:
    output_size: 512
    w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small.pt
    w2v_dir_path: ***/wav2vec_base_noFT
    normalize_before: True
    freeze_finetune_updates: 0

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false
ctc_conf:
    ignore_nan_grad: true

batch_type: folded
batch_size: 8

optim: adam
accum_grad: 1
grad_clip: 5
max_epoch: 100
patience: 30
optim_conf:
    lr: 0.0001
    weight_decay: 0.00001
scheduler: CosineAnnealingLR
scheduler_conf:
    T_max: 100
    eta_min: 0.0000001

use_matplotlib: true
num_att_plot: 0

**Comment by sw005320** [comment]
Can you try the following?
- Remove very long utterances
- Further reduce the batch size (while increasing accum_grad)

**Comment by WZLHQ** [comment]
> Can you try the following?
> 
> * Remove very long utterances
> * Further reduce the batch size (while increasing accum_grad)

thanks. I do the following:
* I set "max_wav_duration" to 5 to remove very long utterances.
* I set "batch size" to 2.  
   * speech.size=torch.Size([1, 91498])
   * I don't know why the first dimension of speech.size is 1 rather than 2.
* "accum_grad" is set to 5

I activate a new conda environment for espnet and re-make. pytorch=2.1.0; pytorch-cuda=12.1, fairseq=1.0.0a0+313ff05; espnet=202310.

the same error occurs, as follows:
*   File "/home/rosie/espnet/espnet2/asr/espnet_model.py", line 261, in forward
    encoder_out, encoder_out_lens = self.encoder(speech, speech_lengths)
  File "/home/rosie/espnet/tools/miniconda/envs/espnet-2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rosie/espnet/tools/miniconda/envs/espnet-2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rosie/espnet/espnet2/asr/encoder/wav2vec2_encoder.py", line 116, in forward
    masks = make_pad_mask(ilens).to(xs_pad.device)
  File "/home/rosie/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 168, in make_pad_mask
    return _make_pad_mask_traceable(lengths, xs, length_dim, maxlen)
  File "/home/rosie/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 249, in _make_pad_mask_traceable
    mask = triu_onnx(mask)[1:, :-1]  # onnx cannot handle diagonal argument.
  File "/home/rosie/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 261, in triu_onnx
    return x * mask
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.80 GiB. GPU 0 has a total capacty of 23.69 GiB of which 7.38 GiB is free. Including non-PyTorch memory, this process has 16.30 GiB memory in use. Of the allocated memory 15.96 GiB is allocated by PyTorch, and 55.08 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

##Note that when I train a branchformer from stratch (encoder: branchformer), there is no errors. It  seems this error only occurs when fine-tuning w2v2 (encoder: wav2vec2). Please help me.

**Comment by sw005320** [comment]
`speech.size=torch.Size([1, 91498])` 
Is 91498 the number of frames or the number of samples?
How long (second) does this audio? 

> ##Note that when I train a branchformer from stratch (encoder: branchformer), there is no errors. It seems this error only occurs when fine-tuning w2v2 (encoder: wav2vec2). Please help me.

Did you train it with the same data?

**Comment by sw005320** [comment]
91498 is too long.
I recommend you check the front-end part to see if you're doing it correctly.
The maximum frame would be 2000 or so. Yours are too large.

**Comment by WZLHQ** [comment]
> 91498 is too long. I recommend you check the front-end part to see if you're doing it correctly. The maximum frame would be 2000 or so. Yours are too large.

Thank you very much.

**Comment by WZLHQ** [comment]
The problem is solved.
This CUDA out-of-memory error may be caused by the version mismatch between espnet, pytorch, and fairseq.
I use the following versions:
* espnet==202301
* fairseq==0.12.2
* pytorch==1.8.1+cuda11.1
By specifying these versions, no errors exist.

If anyone wants to fine-tune wav2vec2 (used as the encoder), this issue might be helpful.
