### ISSUE TITLE
Replicating OWSM 3.1 results on Commonvoice

### ISSUE THREAD

**Issue by mgaido91** [espnet/espnet#6027]
Hi,

thanks for your work and contributions to the community. I am trying to replicate OWSM 3.1 results on CommonVoice, but I am struggling to get results close to those reported in the paper and I am not sure what I am missing.

I paste below my simple code snippet:

```
from espnet2.bin.s2t_inference import Speech2Text
import librosa
import pandas as pd

test_tsv = "..."
audio_basedir = "...."

s2t = Speech2Text.from_pretrained("espnet/owsm_v3.1_ebf", beam_size=3, lang_sym=f'<eng>', task_sym='<asr>', device="cuda")

df = pd.read_csv(test_tsv, sep="\t", header=0, encoding="utf-8", escapechar="\\", na_filter=False)
df = df.reset_index()

for index, row in df.iterrows():
    speech, _ = librosa.load(audio_basedir + "/" + row["path"])
    out = s2t(speech)[0]
    print(out[3])
```

With this I get 24.06 WER, comuputed using the `WhisperNormalizer` and jiwer. As a side note, I had to reduce the beam size from 5 to 3 because I was getting OOM issues on a A40 with 48GB VRAM. Can you please help me in understanding the issue?

Thanks!

**Comment by pyf98** [comment]
Hi, thanks for the question. Here are a few possible differences:

- The version of Common Voice might be different. I think ESPnet is using this one: https://github.com/espnet/espnet/blob/master/egs2/owsm_v3/s2t1/local/prepare_commonvoice.sh
- We used `maxlenratio: 0.4` during decoding. The beam size can be 1 for greedy or 5 for beam search.
- For English, we used Whisper's English text normalizer. Note that Whisper has two normalizers: one for English, and the other for non-English.
- Did you predict the time stamps as well? If so, are those removed before scoring? As a general suggestion, it's always good to check the actual model output and the alignment results to know if there are any unexpected issues (e.g., special tokens, failed decoding, incorrect configs, etc.)
- The audio should be mono (single channel) in 16kHz. It will be padded to 30s, which is done here: https://github.com/espnet/espnet/blob/master/espnet2/bin/s2t_inference.py#L449-L453

**Comment by mgaido91** [comment]
Thank you for your reply @pyf98 .

> The version of Common Voice might be different

Yes, we are using CommonVoice 18, but I do not think this explains going from 8 to 24 of WER.

> We used maxlenratio: 0.4 during decoding. The beam size can be 1 for greedy or 5 for beam search.

I will try with `maxlenratio: 0.4` and let you know. As I wrote in the original post, with beam size 5 I get OOM on a 48GB VRAM, so I was forced to use 3. Do you have any suggestion regarding this?

> For English, we used Whisper's English text normalizer. 

Yes, I did the same.

> Did you predict the time stamps as well?

I have not seen them in the output. The output does not look weird, here you are the first 10 lines:

```
Joe Keaton disapproved of films and Buster also had reservations about the medium.
Should you like?
six
All's well that ends well.
It is a busy market town that serves a large surrounded area.
They're going to decide they've been tonight.
Ilsebet was aboard D. C. Meigas Maria.
Do you know me?
How is most of you are going to bamboo ambiguities by Q and Q?
You are so wounded!
```

Versus the reference:

```
Joe Keaton disapproved of films, and Buster also had reservations about the medium.
She'll be all right.
six
All's well that ends well.
It is a busy market town that serves a large surrounding area.
We are going to the football game tonight.
Elizabeth was about the same age as Maria.
Do you mean it?
How is Mozilla going to handle ambiguities like queue and cue?
You are so rude!
```

I can provide you the full output I get if you want.
Thanks!

**Comment by pyf98** [comment]
Hi @mgaido91 , thanks for the new information.

> Yes, we are using CommonVoice 18, but I do not think this explains going from 8 to 24 of WER.

Where did you find the result of 8? From the [paper](https://arxiv.org/pdf/2401.16658), our result was 12.6. It's still a large gap, so we can check further below.


The output looks weird to me. Is the audio loaded at 16 kHz? `librosa.load()` will load the audio at 22k by default: https://librosa.org/doc/main/generated/librosa.load.html#librosa.load

You can specify the sampling rate explicitly.

![Image](https://github.com/user-attachments/assets/7bba6a81-8f23-4d79-b3fa-fca0095caa92)

**Comment by pyf98** [comment]
For decoding, our main results are obtained with greedy search (beam size = 1).

**Comment by pyf98** [comment]
If you want to reduce memory usage and inference cost, you can install `flash-attn` and add a `bf16` mixed precision context manager when running the inference. I have not tested it on encoder-decoder OWSM, but it significantly reduces the memory for our encoder-only model, [OWSM-CTC](https://huggingface.co/espnet/owsm_ctc_v3.1_1B).

**Comment by mgaido91** [comment]
> Where did you find the result of 8? From the [paper](https://arxiv.org/pdf/2401.16658), our result was 12.6. It's still a large gap, so we can check further below.

Sorry, my bad, I got confused with VoxPopuli.

> The output looks weird to me. Is the audio loaded at 16 kHz? librosa.load() will load the audio at 22k by default

You're right! This may be the issue, I will run the inference again and let you know! Thank you and sorry for wasting your time with my mistake.

PS BTW I added `maxlenratio: 0.4` and the inference became extremely slow (my estimate is that it will take ~16hours for the commonvoice test set vs 3-4 hours without it). Is this slowdown expected?

**Comment by pyf98** [comment]
> PS BTW I added maxlenratio: 0.4 and the inference became extremely slow (my estimate is that it will take ~16hours for the commonvoice test set vs 3-4 hours without it). Is this slowdown expected?

That's weird. This parameter will limit the max decoding steps to "0.4 * encoder output length". Sometimes the decoding will get stuck in repeating a few tokens, therefore limiting the max length can reduce decoding time.

**Comment by mgaido91** [comment]
Yes, I can't understand why this is happening... I am using these versions and it consistently happens:
```
espnet==202412
espnet-model-zoo==0.1.7
```

**Comment by pyf98** [comment]
I'm not aware if there is any significant change in the inference code.

Maybe first fix the sampling rate bug and try your previous setting. If you have time, you can take a closer look at the code or environment.

I checked some of the samples you shared at the beginning. My previous decoding results look good.

```
Scores: (#C #S #D #I) 8 0 0 0
REF:  elizabeth was about the same age as maria 
HYP:  elizabeth was about the same age as maria 
Eval:                                           

Scores: (#C #S #D #I) 4 0 0 0
REF:  do you mean it 
HYP:  do you mean it 
Eval:                

Scores: (#C #S #D #I) 10 1 0 0
REF:  how is mozilla going to handle ambiguities like queue and CUE   
HYP:  how is mozilla going to handle ambiguities like queue and QUEUE 
Eval:                                                           S     

Scores: (#C #S #D #I) 4 0 0 0
REF:  you are so rude 
HYP:  you are so rude 
Eval:      
```

**Comment by pyf98** [comment]
We typically prepare data in ESpnet format and launch the decoding via `s2t.sh`. In that case, my decoding config would look like this:

```
beam_size: 1
penalty: 0.0
maxlenratio: 0.4
minlenratio: 0.0
ctc_weight: 0.0
lm_weight: 0.0
```

**Comment by mgaido91** [comment]
I confirm that the issue was my error with the sampling rate when reading the audio. Thanks and sorry for wasting your time.

For your reference, I got the following results using `beam size: 3`:



| Test set | WER |
| -------- | -------- |
| CV18 en | 11.9 |
| CV18 it | 12.5 |

Adding `maxlenratio: 0.4` did not change the results, although it made the inference very slow (from 3 hours to 20 hours).

Thank you again.

**Comment by pyf98** [comment]
Thanks for the update! Glad to know the error was fixed.
